### Create a customer
POST {{api_base_url}}/api/v0/customers
Content-Type: application/json

{
  "firstName": "Bohort",
  "lastName": "De Gaune",
  "phoneNumber": "0123456789"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.firstName === "Bohort", "Invalid first name");
  client.assert(response.body.lastName === "De Gaune", "Invalid last name");
  client.assert(response.body.phoneNumber === "0123456789", "Invalid phone number");
  client.assert(response.body.id !== null, "Id not generated");
});
%}

### Create a customer with existing phone number
POST {{api_base_url}}/api/v0/customers
Content-Type: application/json

{
  "firstName": "Perceval",
  "lastName": "De Galle",
  "phoneNumber": "0123456789"
}

> {%
client.test("Request failed", function() {
  client.assert(response.status === 500, "Response status is not 500");
});
%}

###
GET {{api_base_url}}/api/v0/customers/phonenumber/0123456789
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.firstName === "Bohort", "Invalid first name");
  client.assert(response.body.lastName === "De Gaune", "Invalid last name");
  client.assert(response.body.phoneNumber === "0123456789", "Invalid phone number");
  client.assert(response.body.id !== null, "Id not generated");
});
%}

###
GET {{api_base_url}}/api/v0/customers/phonenumber/123
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body === null, "Response body is not null");
});
%}

###
GET {{api_base_url}}/api/v0/customers/9/previous_orders
Accept: application/json

> {%
 client.test("Request executed successfully", function() {
     client.assert(response.status === 200, "Request failed");
 })
 %}
