POST {{api_base_url}}/api/v0/menus
Content-Type: application/json

{
  "name": "Le gras c'est la vie",
  "description": "Un repas regroupant les meilleurs création de la légende",
  "tva": 1.5,
  "dishes": []
}

###
GET {{api_base_url}}/api/v0/menus
Accept: application/json

###
PUT {{api_base_url}}/api/v0/menus/1/add_dish/1
Accept: application/json

###
PUT {{api_base_url}}/api/v0/menus/1/remove_dish/1
Accept: application/json

###

