### Create a menu
POST {{api_base_url}}/api/v0/menus
Content-Type: application/json

{
  "name": "Le gras c'est la vie",
  "description": "Un repas regroupant les meilleurs création de la légende",
  "tva": 1.5,
  "dishes": []
}

### List all menus
GET {{api_base_url}}/api/v0/menus
Accept: application/json

### Add a dish
POST {{api_base_url}}/api/v0/menus/1/dish/1
Accept: application/json

### Delete a dish
DELETE /api/v0/menus/1/dish/1
Accept: application/json

###

