POST {{api_base_url}}/api/v0/menus
Content-Type: application/json

{
  "name": "Le gras c'est la vie",
  "description": "Un repas regroupant les meilleurs création de la légende",
  "tva": 1.5,
  "dishes": []
}

###
GET {{api_base_url}}/api/v0/menus
Accept: application/json

###
POST {{api_base_url}}/api/v0/menus/2/dish
Accept: application/json

{
  "dishId": "4"
}

###
DELETE {{api_base_url}}/api/v0/menus/2/dish/4
Accept: application/json

###

