### Create an order
POST {{api_base_url}}/api/v0/orders
Content-Type: application/json
Authorization: Basic admin:adminpwd

{
  "customerId": "1",
  "truckId": "3"
}

### Add a dish to an order
PUT {{api_base_url}}/api/v0/orders/1/dishes
Content-Type: application/json

{
  "dishId": "4"
}

### Add a menu to an order
PUT {{api_base_url}}/api/v0/orders/1/menus
Content-Type: application/json

{
  "menuId": "1"
}
