### Create a truck
POST {{api_base_url}}/api/v0/trucks
Content-Type: application/json
Authorization: {{ admin_authorization_b64 }}


{
  "name": "Roi Loth Truck",
  "description": "Ave Cesar, rosae rosam, et spiritus rex ! Ah non, parce que là, j’en ai marre !"
}

### List all trucks
GET {{api_base_url}}/api/v0/trucks
Accept: application/json
Authorization: {{ user_authorization_b64 }}


###

